### ISSUE TITLE
Unable to load Model

### ISSUE THREAD

**Issue by Jafesu** [Yummiii/sd-webui-forge-docker#9]
Anytime I load a Model into models\Stable-Diffusion my container fails to start

```
reading metadata for /app/sd-webui/models/Stable-diffusion/flux1-dev-fp8.safetensors: OperationalError

Traceback (most recent call last):

  File "/app/sd-webui/modules/sd_models.py", line 89, in __init__

    self.metadata = cache.cached_data_for_file('safetensors-metadata', "checkpoint/" + name, filename, read_metadata)

  File "/app/sd-webui/modules/cache.py", line 104, in cached_data_for_file

    existing_cache = cache(subsection)

  File "/app/sd-webui/modules/cache.py", line 75, in cache

    cache_obj = make_cache(subsection)

  File "/app/sd-webui/modules/cache.py", line 24, in make_cache

    return diskcache.Cache(

  File "/app/sd-webui/venv/lib/python3.10/site-packages/diskcache/core.py", line 480, in __init__

    sql(

  File "/app/sd-webui/venv/lib/python3.10/site-packages/diskcache/core.py", line 666, in _execute_with_retry

    return sql(statement, *args, **kwargs)

sqlite3.OperationalError: disk I/O error

Traceback (most recent call last):

  File "/app/sd-webui/launch.py", line 54, in <module>

    main()

  File "/app/sd-webui/launch.py", line 50, in main

    start()

  File "/app/sd-webui/modules/launch_utils.py", line 549, in start

    import webui

  File "/app/sd-webui/webui.py", line 27, in <module>

    initialize.initialize()

  File "/app/sd-webui/modules/initialize.py", line 68, in initialize

    initialize_rest(reload_script_modules=False)

  File "/app/sd-webui/modules/initialize.py", line 96, in initialize_rest

    sd_models.list_models()

  File "/app/sd-webui/modules/sd_models.py", line 182, in list_models

    checkpoint_info = CheckpointInfo(filename)

  File "/app/sd-webui/modules/sd_models.py", line 98, in __init__

    self.sha256 = hashes.sha256_from_cache(self.filename, f"checkpoint/{name}")

  File "/app/sd-webui/modules/hashes.py", line 34, in sha256_from_cache

    hashes = cache("hashes-addnet") if use_addnet_hash else cache("hashes")

  File "/app/sd-webui/modules/cache.py", line 75, in cache

    cache_obj = make_cache(subsection)

  File "/app/sd-webui/modules/cache.py", line 24, in make_cache

    return diskcache.Cache(

  File "/app/sd-webui/venv/lib/python3.10/site-packages/diskcache/core.py", line 480, in __init__

    sql(

  File "/app/sd-webui/venv/lib/python3.10/site-packages/diskcache/core.py", line 666, in _execute_with_retry

    return sql(statement, *args, **kwargs)

sqlite3.OperationalError: disk I/O error
```

**Comment by Yummiii** [comment]
Hi! Can you please provide me with your docker compose file? also, does this error happen when you try to select (load) a model in the webui or when you copy a file to the directory ?
